name: WaffleCoreNK
main: com.indra87g.Main
version: "${pom.version}"
api: 1.0.0
author: indra87g
description: Core plugin for the WaffleNK ecosystem.
permissions:
  waffle.setblock:
    description: "Allows the user to use the /setblock command"
    default: op
  waffle.servers:
    description: "Allows the user to use the /servers command"
    default: true
  waffle.me:
    description: "Allows the user to use the /me command"
    default: true
