name: ContohPlugin
main: com.indra87g.Main
version: 0.1.0
api: 1.0.0
author: indra87g
description: "Core plugin for the WaffleNK ecosystem."
commands:
  setblock:
    description: "Sets a block at a specific location"
    usage: "/setblock <x> <y> <z> <block_id>"
    permission: waffle.setblock
permissions:
  waffle.setblock:
    description: "Allows the user to use the /setblock command"
    default: op
