name: WaffleCoreNK
main: com.indra87g.Main
version: 0.1.2
api: 1.0.0
author: indra87g
description: Core plugin for the WaffleNK ecosystem.
commands:
  servers:
    description: "Shows a list of available servers."
    permission: waffle.servers
  setblock:
    description: "Sets a block at the player's location. Usage: /setblock <block_id>"
    permission: waffle.setblock
  clearchat:
    description: "Clear your chat"
    permission: waffle.clearchat
  fastmsg:
    description: "Sends a predefined message. Usage: /fastmsg <message_key>"
    permission: waffle.fastmsg
  timer:
    description: "Sets a timer to send a message or run a command."
    usage: "/timer <addmsg|addcmd|remove|agenda>"
    permission: waffle.timer
permissions:
  waffle.servers:
    description: "Allows the user to use the /servers command"
    default: true
  waffle.setblock:
    description: "Allows the user to use the /setblock command"
    default: op
  waffle.clearchat:
    description: "Allows the user to use the /clearchat command"
    default: true
  waffle.fastmsg:
    description: "Allows the user to use the /fastmsg command"
    default: op
  waffle.timer:
    description: "Allows the user to use the /timer command."
    default: true
    children:
      waffle.timer.admin:
        description: "Allows using the addcmd subcommand of /timer."
        default: op