name: Build Nukkit Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '20' # Ganti dengan versi Java sesuai kebutuhan plugin kamu

    - name: Cache Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: maven-${{ runner.os}}-${{ hashFiles('**/pom.xml')}}
        restore-keys: |
          maven-${{ runner.os}}

    - name: Build plugin dengan Maven
      run: mvn clean package

    - name: Upload Plugin JAR
      uses: actions/upload-artifact@v4
      with:
        name: NukkitPlugin
        path: target/*.jar
